version: "2"

name: playground-dev

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/home/playground/metafacture-playground
      - '/etc/timezone:/etc/timezone:ro' # Sync with host
      - '/etc/localtime:/etc/localtime:ro' # Sync with host
    ports:
      - 8280:8280
      - 9630:9630
