version: "2"

name: playground-prod

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    volumes:
      - '/etc/timezone:/etc/timezone:ro' # Sync with host
      - '/etc/localtime:/etc/localtime:ro' # Sync with host
      - './tmp:/home/playground/metafacture-playground/tmp'
    deploy:
      resources:
        limits:
          cpus: '3.0' # number of cores
          memory: 8GB
