version: "2"

name: playground-dev

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/home/playground/metafacture-playground
    ports:
      - 8280:8280
      - 9630:9630