name: Clojure/Clojurescript Build

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout metafacture-core (temporary)
      uses: actions/checkout@v2
      with:
        path: metafacture-core
        repository: metafacture/metafacture-core
        ref: 5.5.1-rc1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install metafacture-core (temporary)
      working-directory: metafacture-core
      run: ./gradlew install
    - name: Checkout metafacture-fix
      uses: actions/checkout@v2
      with:
        path: metafacture-fix
        repository: metafacture/metafacture-fix
        ref: 0.5.1
    - name: Install metafacture-fix
      working-directory: metafacture-fix 
      run: ./gradlew install
    - name: Set up Node.js
      uses: actions/setup-node@v2
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Build cljs
      run: lein release
    - name: Build clj
      run: lein uberjar
